# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "nuget"    
    directory: "/HubPagamento.ApiExterna.API/HubPagamento.ApiExterna.API.csproj"      # Diretório do subprojeto A
    schedule:
      interval: "daily" 
  - package-ecosystem: "nuget"
    directory: "/HubPagamento-ApiExterna.API.DataContracs/HubPagamento.ApiExterna.API.Application.csproj"      # Diretório do subprojeto B
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/HubPagamento-ApiExterna/HubPagamento.ApiExterna.Service/HubPagamento.ApiExterna.Service.csproj" # Diretório do subprojeto de testes
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/HubPagamento-ApiExterna/HubPagamento.ApiExterna.IoC.Configuration/HubPagamento.ApiExterna.IoC.Configuration.csproj" # Diretório do subprojeto de testes
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/HubPagamento-ApiExterna/IntegrationTests/HubPagamento.ApiExterna.IntegrationTests.csproj" # Diretório do subprojeto de testes
    schedule:
      interval: "daily"