# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - release/skywalker/*
    - master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  projectName: '**/HubPagamento.ApiExterna.API.csproj'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: '58501c34-3ac6-481a-83b2-4e2dc29352b1/b99a13c1-13e6-45a0-9cbb-a9a2d2b187b6'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: $(ProjectName)
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Tests
  inputs:
    command: 'test'
    projects: '**/*[Tt]ests*/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --collect:"XPlat Code Coverage"'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(ProjectName)'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact Hub_Pagamento_Api_Externa'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Hub_Pagamento_Api_Externa'
    publishLocation: 'Container'